#!/usr/bin/env python

if __name__ == '__main__':
    from argparse import ArgumentParser
    from sys import stdin
    from tempfile import NamedTemporaryFile
    from disco.comm import request
    from disco.ddfs import DDFS

    parser = ArgumentParser(prog='copy_blobs', description="copy blobs between disco clusters")

    parser.add_argument(
        "-s",
        "--server",
        dest="server",
        help="DDFS server destination",
        default='disco://localhost'
    )

    parser.add_argument(
        "-t",
        "--tag",
        dest="tag",
        help="destination tag to push blobs to",
        default='newtag'
    )

    options = parser.parse_args()

    server = options.server
    if not server.startswith('disco://'):
        server = 'disco://' + server
    ddfs = DDFS(server)

    # read list of blobs from stdin, assume disco:// or http://...:8989 style urls - either way, there should only be 1
    # blob per line
    for blob_url in stdin:
        blob_req = request('GET', blob_url)
        with NamedTemporaryFile("w", delete=True) as fd:
            while True:
                bites = blob_req.read(8192)
                if bites:
                    fd.write(bites)
                else:
                    break
            fd.flush()
            ddfs.push(options.tag, [fd.name])
            print "Pushed %s to %s:%s" % (blob_url, server, options.tag)
